---
title: Bem-vindo ao meu mundo
hero_image: images/banner.png
description: Crie um mundo 2.5D para explorar e interagir.
meta_title: Projetos de codificação Scratch para crianças e adolescentes | Meu mundo
meta_description: Aprenda a codificar no Scratch com os projetos de codificação da Fundação Raspberry Pi para crianças e adolescentes. Construa um mundo 2.5D no Scratch para explorar e interagir.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: Você vai fazer
  - 
    title: A sua ideia
  - 
    title: Construir e testar
    completion:
      - engaged
      - internal
  - 
    title: Lista de tarefas
    completion:
      - external
  - 
    title: Melhore o seu projeto
  - 
    title: Compartilhar
