---
title: Bienvenue dans mon monde
hero_image: images/banner.png
description: Construire un monde 2.5D pour explorer et interagir avec.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: You will make
  - 
    title: Ton idée
  - 
    title: Construire et tester
    completion:
      - engaged
      - internal
  - 
    title: Checklist
    completion:
      - external
  - 
    title: Améliorer ton projet
  - 
    title: Partager
  - 
    title: Et ensuite ?
